import {useEffect,useState} from 'react';
import {Award,Star,Sparkles,Lock,Check} from 'lucide-react';
import {useSession} from '../../core/session';
import {useClassroom} from '../../core/classroom';
import {api} from '../../core/api';
import {EmptyState,ErrorMessage} from '../../core/ui';
import {type Awards,formatDate} from './types';
import './homework.css';
export default function AwardsPage(){const {classId,studentId,students}=useClassroom(),{user}=useSession();return <AwardsWorkspace key={`${classId}:${studentId}`} classId={classId} selectedStudent={studentId} students={students} teacher={user!.role==='teacher'}/>;}
function AwardsWorkspace({classId,selectedStudent,students,teacher}:{classId:string;selectedStudent:string;students:{id:string;fullName:string}[];teacher:boolean}){const [studentId,setStudentId]=useState(selectedStudent||students[0]?.id||'');return <section className="hw-page"><div className="page-heading"><div><span className="eyebrow">КАЖДОЕ СТАРАНИЕ ИМЕЕТ ЗНАЧЕНИЕ</span><h1>Есть чем гордиться <span className="heading-spark">✦</span></h1><p>Маленькие победы, которые складываются в большую историю.</p></div></div>{teacher&&students.length>0&&<label className="field hw-award-select"><span>Достижения ученика</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option value={s.id} key={s.id}>{s.fullName}</option>)}</select></label>}{studentId?<StudentAwards key={studentId} classId={classId} studentId={studentId}/>:<EmptyState title="У каждого будет своя история успеха" description="Добавьте ученика, чтобы видеть его достижения." icon={<Award size={30}/>}/>}</section>;}
function StudentAwards({classId,studentId}:{classId:string;studentId:string}){const [data,setData]=useState<Awards|null>(null),[error,setError]=useState('');useEffect(()=>{let active=true;api<Awards>(`/api/classes/${classId}/awards?studentId=${encodeURIComponent(studentId)}`).then(result=>{if(active)setData(result);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[classId,studentId]);return <><ErrorMessage message={error}/>{!data&&!error?<p role="status" className="muted">Собираем достижения…</p>:data&&<><div className="hw-banner awards-banner"><span className="hw-banner-icon"><Sparkles size={31}/></span><div><h2>Старание превращается в достижения</h2><p>Бейджи за 1, 5 и 10 разных выполненных заданий. Полученные награды остаются навсегда, даже если снять отметку выполнения.</p></div><span className="hw-banner-number">{data.awards.length}<small>наград</small></span></div><div className="section-heading"><div><h2>Коллекция достижений</h2><p>Сейчас выполнено заданий: {data.completedCount}. Без сравнений и рейтингов — только свой путь.</p></div></div><div className="hw-badge-grid">{data.badges.map((badge,i)=>{const earned=data.awards.find(a=>a.badgeKey===badge.key),progress=Math.min(data.completedCount,badge.threshold);const Icon=[Star,Sparkles,Award][i];return <article className={`hw-badge ${earned?'earned':''} hw-badge-${i}`} key={badge.key}><span className="hw-badge-mark">{earned?<Check size={14}/>:<Lock size={13}/>}</span><div className="hw-badge-icon"><Icon size={38} strokeWidth={1.5}/></div><h3>{badge.title}</h3><p>{badge.description}</p><progress value={earned?badge.threshold:progress} max={badge.threshold} aria-label={`${badge.title}: ${earned?'получено':`${progress} из ${badge.threshold}`}`}/><small>{earned?`Получено ${formatDate(earned.createdAt)}`:`${progress} из ${badge.threshold} · всё впереди`}</small></article>;})}</div><div className="section-heading hw-praise-heading"><div><h2>Тёплые слова учителя</h2><p>Особенные награды за внимание и старание.</p></div></div>{data.awards.filter(a=>a.kind==='manual').length?<div className="hw-praise-grid">{data.awards.filter(a=>a.kind==='manual').map(a=><article className="hw-praise-card" key={a.id}><span className="hw-praise-icon"><Award size={24}/></span><div><h3>{a.title}</h3><p>{a.message}</p><small>{formatDate(a.createdAt)}</small></div></article>)}</div>:<EmptyState title="Добрые слова ещё впереди" description="Когда учитель выдаст награду за выполненное задание, она появится здесь." icon={<Award size={28}/>}/>}</>}</>;}
