import {useEffect,useState,type FormEvent} from 'react';
import {Plus,NotebookPen,Check,Clock,ArrowUpRight,Award,Trash2,Pencil} from 'lucide-react';
import {useSession} from '../../core/session';
import {useClassroom} from '../../core/classroom';
import {api} from '../../core/api';
import {Button,Dialog,EmptyState,ErrorMessage} from '../../core/ui';
import {type Homework,formatDate} from './types';
import './homework.css';
import HomeworkEditor from './HomeworkEditor';
export default function HomeworkPage(){const {user}=useSession(),{classId,studentId,students}=useClassroom();return <HomeworkWorkspace key={`${classId}:${studentId}`} classId={classId} studentId={studentId} students={students} role={user!.role}/>;}
function HomeworkWorkspace({classId,studentId,students,role}:{classId:string;studentId:string;students:{id:string;fullName:string}[];role:string}){
 const teacher=role==='teacher',query=!teacher&&studentId?`?studentId=${encodeURIComponent(studentId)}`:'';
 const [items,setItems]=useState<Homework[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[editing,setEditing]=useState<Homework|'new'|null>(null),[detail,setDetail]=useState<string|null>(null),[deleting,setDeleting]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[praiseStudent,setPraiseStudent]=useState(''),[success,setSuccess]=useState(''),[refreshError,setRefreshError]=useState(''),[refreshing,setRefreshing]=useState(false);
 async function refresh(){setRefreshing(true);setRefreshError('');try{const data=await api<Homework[]>(`/api/classes/${classId}/homework${query}`);setItems(data);}catch(e){setRefreshError(`Изменение сохранено, но список не удалось обновить. ${(e as Error).message}`);}finally{setRefreshing(false);}}
 useEffect(()=>{let active=true;api<Homework[]>(`/api/classes/${classId}/homework${query}`).then(data=>{if(active)setItems(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[classId,query]);
 const chosen=items.find(h=>h.id===detail),isDone=(h:Homework)=>teacher?h.studentCount>0&&h.completedCount===h.studentCount:h.completed;
 const shown=items.filter(h=>filter==='all'||(filter==='done'?isDone(h):!isDone(h)));
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setFormError('');try{const saved=await api<Homework>(editing==='new'?`/api/classes/${classId}/homework`:`/api/homework/${(editing as Homework).id}`,{method:editing==='new'?'POST':'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});setItems(old=>[...old.filter(item=>item.id!==saved.id),saved].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.id.localeCompare(b.id)));setEditing(null);setSuccess('Задание сохранено');await refresh();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function complete(h:Homework){setBusy(true);setError('');try{const updated=await api<Homework>(`/api/homework/${h.id}/completion`,{method:'PUT',body:JSON.stringify({completed:!h.completed})});setItems(old=>old.map(item=>item.id===updated.id?updated:item));setSuccess(updated.completed?'Готово! Загляните в достижения — каждый шаг важен.':'Отметка выполнения снята');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="hw-page"><div className="page-heading"><div><span className="eyebrow">ШАГ ЗА ШАГОМ К НОВЫМ ЗНАНИЯМ</span><h1>Домашние задания <span className="heading-spark">✦</span></h1><p>Всё, что нужно для следующего маленького открытия.</p></div>{teacher&&<Button onClick={()=>{setFormError('');setEditing('new');}}><Plus size={17}/>Добавить задание</Button>}</div><div className="hw-banner"><span className="hw-banner-icon"><NotebookPen size={30}/></span><div><h2>{teacher?'Поддерживать. Замечать. Вдохновлять.':'Большой путь начинается с одного шага'}</h2><p>{teacher?'Следите за выполнением и отмечайте старание тёплыми словами.':'Отмечайте готовые задания и собирайте достижения за старание.'}</p></div><span className="hw-banner-number">{items.length}<small>заданий</small></span></div><div className="hw-filters" aria-label="Фильтр заданий">{[['all','Все задания'],['open','Открытые'],['done','Выполненные']].map(([key,label])=><button key={key} aria-pressed={filter===key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div><ErrorMessage message={error}/>{refreshError&&<div><ErrorMessage message={refreshError}/><Button type="button" variant="secondary" disabled={refreshing} onClick={()=>void refresh()}>{refreshing?'Обновляем…':'Обновить список'}</Button></div>}{success&&<p className="hw-success" role="status">{success}</p>}{loading?<p role="status" className="muted">Загружаем задания…</p>:!shown.length?<EmptyState title={items.length?'В этом списке пока пусто':'Здесь начнутся новые открытия'} description={items.length?'Выберите другой фильтр, чтобы увидеть задания.':teacher?'Добавьте первое задание — ученики увидят его в своём пространстве.':'Когда учитель добавит задания, они появятся здесь.'} icon={<NotebookPen size={28}/>}/>:<div className="hw-grid">{shown.map(h=><article className={`hw-card ${isDone(h)?'done':''}`} key={h.id}><div className="hw-card-top"><span className="hw-subject">{h.subject}</span><span className={`hw-status ${isDone(h)?'completed':''}`}>{isDone(h)?<Check size={13}/>:<Clock size={13}/>}{isDone(h)?'Выполнено':'В работе'}</span></div><button className="hw-title" onClick={()=>{setDetail(h.id);setError('');setSuccess('');}}>{h.title}<ArrowUpRight size={19}/></button><p className="hw-preview">{h.description||'Откройте задание, чтобы посмотреть подробности.'}</p><div className="hw-card-bottom"><span>До {formatDate(h.dueDate)}</span>{teacher?<span>{h.completedCount} из {h.studentCount} выполнили</span>:role==='student'?<Button variant={h.completed?'secondary':'primary'} disabled={busy} onClick={()=>complete(h)}>{h.completed?'Снять отметку':'Готово'}{!h.completed&&<Check size={14}/>}</Button>:<span>{h.completed?'Готово':'Ожидает выполнения'}</span>}</div></article>)}</div>}
 {editing&&<HomeworkEditor key={editing==='new'?'new':editing.id} classId={classId} homework={editing==='new'?null:editing} busy={busy} error={formError} onSubmit={save} onClose={()=>setEditing(null)}/>}
 {chosen&&!editing&&!deleting&&<Dialog title={chosen.title} onClose={()=>{if(!busy){setDetail(null);setPraiseStudent('');}}}><div className="hw-detail-meta"><span className="hw-subject">{chosen.subject}</span><span>До {formatDate(chosen.dueDate)}</span></div><p className="hw-description">{chosen.description||'Дополнительного описания нет.'}</p>{teacher?<><div className="hw-detail-actions"><Button variant="secondary" onClick={()=>{setFormError('');setEditing(chosen);}}><Pencil size={15}/>Изменить</Button><Button variant="ghost" onClick={()=>{setFormError('');setDeleting(true);}}><Trash2 size={15}/>Удалить</Button></div><h3 className="hw-overview-title">Выполнение · {chosen.completedCount} из {students.length}</h3>{!students.length?<p>Добавьте учеников в разделе «Мой класс».</p>:<div className="hw-student-list">{students.map(s=>{const done=chosen.completions.some(c=>c.studentId===s.id);return <div className="hw-student-row" key={s.id}><span className={`hw-dot ${done?'completed':''}`}>{done?<Check size={14}/>:<Clock size={14}/>}</span><strong>{s.fullName}</strong>{done?<Button variant="ghost" disabled={busy} onClick={()=>{setPraiseStudent(s.id);setFormError('');setSuccess('');}}><Award size={15}/>Наградить</Button>:<small>В работе</small>}</div>;})}</div>}{praiseStudent&&<form className="hw-praise" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setFormError('');try{await api(`/api/homework/${chosen.id}/awards`,{method:'POST',body:JSON.stringify({studentId:praiseStudent,message:data.message})});setPraiseStudent('');setSuccess('Награда сохранена и видна ученику и родителю. Повторная выдача не создаёт копию.');}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}><strong>Тёплые слова для {students.find(s=>s.id===praiseStudent)?.fullName}</strong><p>Одна награда за задание. Уже выданная награда останется прежней.</p><label className="field"><span>За что похвалим?</span><textarea name="message" required maxLength={1000} rows={3}/></label><ErrorMessage message={formError}/><Button disabled={busy}>{busy?'Сохраняем…':'Выдать награду'}</Button></form>}</>:role==='student'?<Button disabled={busy} onClick={()=>complete(chosen)}>{chosen.completed?'Снять отметку выполнения':'Отметить выполненным'}</Button>:<p>{chosen.completed?'Задание выполнено':'Ученик ещё не отметил выполнение'}</p>}<ErrorMessage message={error}/>{success&&<p className="hw-success" role="status">{success}</p>}</Dialog>}
 {chosen&&deleting&&<Dialog title="Удалить задание?" onClose={()=>{if(!busy)setDeleting(false);}}><p>«{chosen.title}» и отметки выполнения будут удалены. Заслуженные награды сохранятся.</p><ErrorMessage message={formError}/><div className="form-actions"><Button variant="secondary" disabled={busy} onClick={()=>setDeleting(false)}>Отмена</Button><Button variant="danger" disabled={busy} onClick={async()=>{setBusy(true);setFormError('');try{await api(`/api/homework/${chosen.id}`,{method:'DELETE'});setItems(old=>old.filter(item=>item.id!==chosen.id));setDetail(null);setDeleting(false);setSuccess('Задание удалено');await refresh();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Удаляем…':'Удалить'}</Button></div></Dialog>}
 </section>;
}
