export function registerHomeworkRoutes(app,ctx){
 const {db,requireUser,requireTeacher,accessibleStudentIds,HttpError,text,date,id}=ctx;
 const select=(req,classId)=>{const ids=accessibleStudentIds(req.user,classId);const chosen=req.query.studentId;if(chosen!==undefined&&(typeof chosen!=='string'||!ids.includes(chosen)))throw new HttpError(403,'Этот ученик недоступен');return chosen?[chosen]:ids;};
 const get=(req)=>{const row=db.prepare('SELECT * FROM homework WHERE id=?').get(req.params.id);if(!row)throw new HttpError(404,'Задание не найдено');select(req,row.class_id);return row;};
 const dto=(row,req)=>{const ids=select(req,row.class_id);const completions=db.prepare('SELECT student_id,completed_at FROM completions WHERE homework_id=?').all(row.id).filter(c=>ids.includes(c.student_id)).map(c=>({studentId:c.student_id,completedAt:c.completed_at}));return {id:row.id,classId:row.class_id,subject:row.subject,title:row.title,description:row.description,dueDate:row.due_date,createdAt:row.created_at,updatedAt:row.updated_at,completions,completed:completions.length>0,completedCount:completions.length,studentCount:ids.length};};
 const fields=(body)=>[text(body.subject,'Предмет',100),text(body.title,'Заголовок',200),text(body.description??'','Описание',5000,false),date(body.dueDate,'Срок')];
 app.get('/api/classes/:id/homework',requireUser,(req,res)=>{select(req,req.params.id);res.json(db.prepare('SELECT * FROM homework WHERE class_id=? ORDER BY due_date,id').all(req.params.id).map(row=>dto(row,req)));});
 app.post('/api/classes/:id/homework',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const values=fields(req.body),key=id(),now=new Date().toISOString();db.prepare('INSERT INTO homework(id,class_id,subject,title,description,due_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(key,req.params.id,...values,now,now);res.status(201).json(dto(db.prepare('SELECT * FROM homework WHERE id=?').get(key),req));});
 app.get('/api/homework/:id',requireUser,(req,res)=>res.json(dto(get(req),req)));
 app.put('/api/homework/:id',requireUser,(req,res)=>{const row=get(req);requireTeacher(req.user,row.class_id);db.prepare('UPDATE homework SET subject=?,title=?,description=?,due_date=?,updated_at=? WHERE id=?').run(...fields(req.body),new Date().toISOString(),row.id);res.json(dto(get(req),req));});
 app.delete('/api/homework/:id',requireUser,(req,res)=>{const row=get(req);requireTeacher(req.user,row.class_id);db.prepare('DELETE FROM homework WHERE id=?').run(row.id);res.status(204).end();});

 const badges=[{key:'completed_1',threshold:1,title:'Первый шаг',description:'Выполнить первое задание'},{key:'completed_5',threshold:5,title:'Отличный ритм',description:'Выполнить 5 разных заданий'},{key:'completed_10',threshold:10,title:'Мастер старания',description:'Выполнить 10 разных заданий'}];
 const transaction=(fn)=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}};
 const count=(studentId,classId)=>Number(db.prepare('SELECT COUNT(*) AS n FROM completions c JOIN homework h ON h.id=c.homework_id WHERE c.student_id=? AND h.class_id=?').get(studentId,classId).n);
 const awardDto=r=>({id:r.id,classId:r.class_id,studentId:r.student_id,homeworkId:r.homework_id,kind:r.kind,badgeKey:r.badge_key,title:r.title,message:r.message,createdAt:r.created_at});
 app.put('/api/homework/:id/completion',requireUser,(req,res)=>{const row=get(req);if(req.user.role!=='student')throw new HttpError(403,'Отметить выполнение может только сам ученик');const studentId=accessibleStudentIds(req.user,row.class_id)[0];if(req.body.studentId!==undefined&&req.body.studentId!==studentId)throw new HttpError(403,'Нельзя изменить отметку другого ученика');if(typeof req.body.completed!=='boolean')throw new HttpError(400,'Укажите состояние выполнения');transaction(()=>{if(req.body.completed){db.prepare('INSERT OR IGNORE INTO completions(homework_id,student_id,completed_at) VALUES(?,?,?)').run(row.id,studentId,new Date().toISOString());const completed=count(studentId,row.class_id);for(const badge of badges)if(completed>=badge.threshold)db.prepare("INSERT OR IGNORE INTO awards(id,class_id,student_id,kind,badge_key,title,message,created_at) VALUES(?,?,?,'automatic',?,?,?,?)").run(id(),row.class_id,studentId,badge.key,badge.title,badge.description,new Date().toISOString());}else db.prepare('DELETE FROM completions WHERE homework_id=? AND student_id=?').run(row.id,studentId);});res.json(dto(row,req));});
 app.get('/api/classes/:id/awards',requireUser,(req,res)=>{const ids=select(req,req.params.id);const studentId=ids.length===1?ids[0]:null;const awards=db.prepare('SELECT * FROM awards WHERE class_id=? ORDER BY created_at DESC,id').all(req.params.id).filter(r=>ids.includes(r.student_id)).map(awardDto);res.json({studentId,completedCount:studentId?count(studentId,req.params.id):0,badges,awards});});

 app.post('/api/homework/:id/awards',requireUser,(req,res)=>{const row=get(req);requireTeacher(req.user,row.class_id);const studentId=text(req.body.studentId,'Ученик',100),message=text(req.body.message,'Похвала',1000);if(!accessibleStudentIds(req.user,row.class_id).includes(studentId))throw new HttpError(403,'Этот ученик недоступен');let created=false;const award=transaction(()=>{const existing=db.prepare("SELECT * FROM awards WHERE student_id=? AND homework_id=? AND kind='manual'").get(studentId,row.id);if(existing)return existing;if(!db.prepare('SELECT 1 FROM completions WHERE student_id=? AND homework_id=?').get(studentId,row.id))throw new HttpError(409,'Сначала ученик должен отметить задание выполненным');const key=id();db.prepare("INSERT INTO awards(id,class_id,student_id,homework_id,kind,title,message,awarded_by,created_at) VALUES(?,?,?,?,'manual',?,?,?,?)").run(key,row.class_id,studentId,row.id,'За отличную работу',message,req.user.id,new Date().toISOString());created=true;return db.prepare('SELECT * FROM awards WHERE id=?').get(key);});res.status(created?201:200).json(awardDto(award));});
}
