export function registerScheduleRoutes(app,ctx){
 const {db,requireUser,requireTeacher,accessibleStudentIds,HttpError,text,id}=ctx;
 const integer=(value,label,max)=>{if(!Number.isInteger(value)||value<1||value>max)throw new HttpError(400,`${label}: укажите целое число от 1 до ${max}`);return value;};
 const lessonDto=row=>({id:row.id,classId:row.class_id,dayOfWeek:row.day_of_week,lessonNumber:row.lesson_number,subject:row.subject,room:row.room});
 const objectBody=value=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new HttpError(400,'Проверьте данные запроса');return value;};
 const validateLesson=raw=>{const body=objectBody(raw);if(body.lessonNumber!==undefined)integer(body.lessonNumber,'Номер урока',20);return {day:integer(body.dayOfWeek,'День недели',7),subject:text(body.subject,'Предмет',120),room:text(body.room??'','Кабинет',60,false)};};
 const find=(table,classId,itemId)=>{const row=db.prepare(`SELECT * FROM ${table} WHERE class_id=? AND id=?`).get(classId,itemId);if(!row)throw new HttpError(404,'Запись не найдена');return row;};
 const list=classId=>db.prepare('SELECT * FROM lessons WHERE class_id=? ORDER BY day_of_week,lesson_number').all(classId);
 const dayRows=(classId,day)=>db.prepare('SELECT * FROM lessons WHERE class_id=? AND day_of_week=? ORDER BY lesson_number').all(classId,day);
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}};
 // No table references lessons. Reinsert the affected day with unchanged IDs inside
 // one transaction: temporary numbers would violate the existing 1..20 CHECK.
 const writeDay=(classId,day,rows)=>{if(rows.length>20)throw new HttpError(409,'В одном дне может быть не больше 20 уроков');db.prepare('DELETE FROM lessons WHERE class_id=? AND day_of_week=?').run(classId,day);const insert=db.prepare('INSERT INTO lessons(id,class_id,day_of_week,lesson_number,subject,room) VALUES(?,?,?,?,?,?)');rows.forEach((row,index)=>insert.run(row.id,classId,day,index+1,row.subject,row.room));};
 app.get('/api/classes/:id/lessons',requireUser,(req,res)=>{accessibleStudentIds(req.user,req.params.id);res.json(list(req.params.id).map(lessonDto));});
 app.post('/api/classes/:id/lessons',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const value=validateLesson(req.body),itemId=id();transaction(()=>writeDay(req.params.id,value.day,[...dayRows(req.params.id,value.day),{id:itemId,subject:value.subject,room:value.room}]));res.status(201).json(lessonDto(find('lessons',req.params.id,itemId)));});
 app.put('/api/classes/:id/lessons/order',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const body=objectBody(req.body),day=integer(body.dayOfWeek,'День недели',7),ids=body.lessonIds;if(!Array.isArray(ids)||ids.length>20||ids.some(value=>typeof value!=='string'||!value.trim()||value.length>100)||new Set(ids).size!==ids.length)throw new HttpError(400,'Передайте список уникальных идентификаторов уроков');transaction(()=>{const rows=dayRows(req.params.id,day),byId=new Map(rows.map(row=>[row.id,row]));if(rows.length!==ids.length||ids.some(itemId=>!byId.has(itemId)))throw new HttpError(409,'Расписание изменилось. Обновите страницу и повторите перестановку');writeDay(req.params.id,day,ids.map(itemId=>byId.get(itemId)));});res.json(list(req.params.id).map(lessonDto));});
 app.put('/api/classes/:id/lessons/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const value=validateLesson(req.body);transaction(()=>{const old=find('lessons',req.params.id,req.params.itemId),updated={...old,subject:value.subject,room:value.room};if(old.day_of_week===value.day)writeDay(req.params.id,value.day,dayRows(req.params.id,value.day).map(row=>row.id===old.id?updated:row));else{const target=dayRows(req.params.id,value.day);if(target.length>=20)throw new HttpError(409,'В одном дне может быть не больше 20 уроков');writeDay(req.params.id,old.day_of_week,dayRows(req.params.id,old.day_of_week).filter(row=>row.id!==old.id));writeDay(req.params.id,value.day,[...target,updated]);}});res.json(lessonDto(find('lessons',req.params.id,req.params.itemId)));});
 app.delete('/api/classes/:id/lessons/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);transaction(()=>{const old=find('lessons',req.params.id,req.params.itemId);writeDay(req.params.id,old.day_of_week,dayRows(req.params.id,old.day_of_week).filter(row=>row.id!==old.id));});res.sendStatus(204);});

 const bellDto=row=>({id:row.id,classId:row.class_id,lessonNumber:row.lesson_number,startTime:row.start_time,endTime:row.end_time});
 const validateBell=(body={})=>{const number=integer(body.lessonNumber,'Номер урока',20);for(const value of [body.startTime,body.endTime])if(typeof value!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new HttpError(400,'Укажите время в формате ЧЧ:ММ');if(body.startTime>=body.endTime)throw new HttpError(400,'Начало урока должно быть раньше окончания');return {number,start:body.startTime,end:body.endTime};};
 const checkBell=(classId,value,except='')=>{if(db.prepare('SELECT id FROM bells WHERE class_id=? AND id<>? AND (lesson_number=? OR (start_time<? AND end_time>?))').get(classId,except,value.number,value.end,value.start))throw new HttpError(409,'Номер урока занят или время пересекается с другим звонком');};
 app.get('/api/classes/:id/bells',requireUser,(req,res)=>{accessibleStudentIds(req.user,req.params.id);res.json(db.prepare('SELECT * FROM bells WHERE class_id=? ORDER BY lesson_number').all(req.params.id).map(bellDto));});
 app.post('/api/classes/:id/bells',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const value=validateBell(req.body);checkBell(req.params.id,value);const itemId=id();db.prepare('INSERT INTO bells(id,class_id,lesson_number,start_time,end_time) VALUES(?,?,?,?,?)').run(itemId,req.params.id,value.number,value.start,value.end);res.status(201).json(bellDto(find('bells',req.params.id,itemId)));});
 app.put('/api/classes/:id/bells/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('bells',req.params.id,req.params.itemId);const value=validateBell(req.body);checkBell(req.params.id,value,req.params.itemId);db.prepare('UPDATE bells SET lesson_number=?,start_time=?,end_time=? WHERE class_id=? AND id=?').run(value.number,value.start,value.end,req.params.id,req.params.itemId);res.json(bellDto(find('bells',req.params.id,req.params.itemId)));});
 app.delete('/api/classes/:id/bells/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('bells',req.params.id,req.params.itemId);db.prepare('DELETE FROM bells WHERE class_id=? AND id=?').run(req.params.id,req.params.itemId);res.sendStatus(204);});
}
