export function registerScheduleRoutes(app,ctx){
 const {db,requireUser,requireTeacher,accessibleStudentIds,HttpError,text,id}=ctx;
 const integer=(value,label,max)=>{if(!Number.isInteger(value)||value<1||value>max)throw new HttpError(400,`${label}: укажите целое число от 1 до ${max}`);return value;};
 const lessonDto=row=>({id:row.id,classId:row.class_id,dayOfWeek:row.day_of_week,lessonNumber:row.lesson_number,subject:row.subject,room:row.room});
 const validateLesson=(body={})=>({day:integer(body.dayOfWeek,'День недели',7),number:integer(body.lessonNumber,'Номер урока',20),subject:text(body.subject,'Предмет',120),room:text(body.room??'','Кабинет',60,false)});
 const find=(table,classId,itemId)=>{const row=db.prepare(`SELECT * FROM ${table} WHERE class_id=? AND id=?`).get(classId,itemId);if(!row)throw new HttpError(404,'Запись не найдена');return row;};
 const checkSlot=(classId,value,except='')=>{if(db.prepare('SELECT id FROM lessons WHERE class_id=? AND day_of_week=? AND lesson_number=? AND id<>?').get(classId,value.day,value.number,except))throw new HttpError(409,'Этот номер урока уже занят в выбранный день');};
 app.get('/api/classes/:id/lessons',requireUser,(req,res)=>{accessibleStudentIds(req.user,req.params.id);res.json(db.prepare('SELECT * FROM lessons WHERE class_id=? ORDER BY day_of_week,lesson_number').all(req.params.id).map(lessonDto));});
 app.post('/api/classes/:id/lessons',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const value=validateLesson(req.body);checkSlot(req.params.id,value);const itemId=id();db.prepare('INSERT INTO lessons(id,class_id,day_of_week,lesson_number,subject,room) VALUES(?,?,?,?,?,?)').run(itemId,req.params.id,value.day,value.number,value.subject,value.room);res.status(201).json(lessonDto(find('lessons',req.params.id,itemId)));});
 app.put('/api/classes/:id/lessons/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('lessons',req.params.id,req.params.itemId);const value=validateLesson(req.body);checkSlot(req.params.id,value,req.params.itemId);db.prepare('UPDATE lessons SET day_of_week=?,lesson_number=?,subject=?,room=? WHERE class_id=? AND id=?').run(value.day,value.number,value.subject,value.room,req.params.id,req.params.itemId);res.json(lessonDto(find('lessons',req.params.id,req.params.itemId)));});
 app.delete('/api/classes/:id/lessons/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('lessons',req.params.id,req.params.itemId);db.prepare('DELETE FROM lessons WHERE class_id=? AND id=?').run(req.params.id,req.params.itemId);res.sendStatus(204);});

 const bellDto=row=>({id:row.id,classId:row.class_id,lessonNumber:row.lesson_number,startTime:row.start_time,endTime:row.end_time});
 const validateBell=(body={})=>{const number=integer(body.lessonNumber,'Номер урока',20);for(const value of [body.startTime,body.endTime])if(typeof value!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))throw new HttpError(400,'Укажите время в формате ЧЧ:ММ');if(body.startTime>=body.endTime)throw new HttpError(400,'Начало урока должно быть раньше окончания');return {number,start:body.startTime,end:body.endTime};};
 const checkBell=(classId,value,except='')=>{if(db.prepare('SELECT id FROM bells WHERE class_id=? AND id<>? AND (lesson_number=? OR (start_time<? AND end_time>?))').get(classId,except,value.number,value.end,value.start))throw new HttpError(409,'Номер урока занят или время пересекается с другим звонком');};
 app.get('/api/classes/:id/bells',requireUser,(req,res)=>{accessibleStudentIds(req.user,req.params.id);res.json(db.prepare('SELECT * FROM bells WHERE class_id=? ORDER BY lesson_number').all(req.params.id).map(bellDto));});
 app.post('/api/classes/:id/bells',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);const value=validateBell(req.body);checkBell(req.params.id,value);const itemId=id();db.prepare('INSERT INTO bells(id,class_id,lesson_number,start_time,end_time) VALUES(?,?,?,?,?)').run(itemId,req.params.id,value.number,value.start,value.end);res.status(201).json(bellDto(find('bells',req.params.id,itemId)));});
 app.put('/api/classes/:id/bells/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('bells',req.params.id,req.params.itemId);const value=validateBell(req.body);checkBell(req.params.id,value,req.params.itemId);db.prepare('UPDATE bells SET lesson_number=?,start_time=?,end_time=? WHERE class_id=? AND id=?').run(value.number,value.start,value.end,req.params.id,req.params.itemId);res.json(bellDto(find('bells',req.params.id,req.params.itemId)));});
 app.delete('/api/classes/:id/bells/:itemId',requireUser,(req,res)=>{requireTeacher(req.user,req.params.id);find('bells',req.params.id,req.params.itemId);db.prepare('DELETE FROM bells WHERE class_id=? AND id=?').run(req.params.id,req.params.itemId);res.sendStatus(204);});
}
