import {useEffect,useRef,useState,type FormEvent} from 'react';
import {BookOpen,Clock3,Pencil,Plus,Trash2,CalendarDays} from 'lucide-react';
import {api} from '../../core/api';
import {useClassroom} from '../../core/classroom';
import {useSession} from '../../core/session';
import {Button,Dialog,EmptyState,ErrorMessage,Input} from '../../core/ui';
import SortableLessonList from './SortableLessonList';
import './schedule.css';
export type Lesson={id:string;classId:string;dayOfWeek:number;lessonNumber:number;subject:string;room:string};
export type Bell={id:string;classId:string;lessonNumber:number;startTime:string;endTime:string};
type Editor={kind:'lessons';item?:Lesson}|{kind:'bells';item?:Bell};
const days=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const shortDays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const errorText=(e:unknown)=>e instanceof Error?e.message:'Не удалось выполнить запрос. Попробуйте ещё раз.';
export default function SchedulePage(){const {classId}=useClassroom();return <Schedule key={classId} classId={classId}/>;}
function Schedule({classId}:{classId:string}){
 const {user}=useSession(),teacher=user?.role==='teacher';
 const [lessons,setLessons]=useState<Lesson[]>([]),[bells,setBells]=useState<Bell[]>([]),[day,setDay]=useState((new Date().getDay()+6)%7+1);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<Editor|null>(null);
 const [deletion,setDeletion]=useState<Editor|null>(null),[pending,setPending]=useState(false),[deleteError,setDeleteError]=useState('');
 const [orderError,setOrderError]=useState(''),[refreshError,setRefreshError]=useState(''),[needsRefresh,setNeedsRefresh]=useState(false),[dragging,setDragging]=useState(false),[notice,setNotice]=useState('');
 const lock=useRef(false),mounted=useRef(true),base=`/api/classes/${classId}`;
 const read=()=>Promise.all([api<Lesson[]>(`${base}/lessons`),api<Bell[]>(`${base}/bells`)]);
 useEffect(()=>{mounted.current=true;read().then(([l,b])=>{if(mounted.current){setLessons(l);setBells(b);}}).catch(e=>{if(mounted.current)setError(errorText(e));}).finally(()=>{if(mounted.current)setLoading(false);});return()=>{mounted.current=false;};},[base]);
 const todayLessons=lessons.filter(l=>l.dayOfWeek===day).sort((a,b)=>a.lessonNumber-b.lessonNumber);
 const blocked=pending||dragging||needsRefresh;
 const release=()=>{lock.current=false;if(mounted.current)setPending(false);};
 async function refresh(){if(lock.current)return;lock.current=true;setPending(true);try{const [l,b]=await read();if(mounted.current){setLessons(l);setBells(b);setError('');setRefreshError('');setOrderError('');setNeedsRefresh(false);}}catch(e){if(mounted.current){setRefreshError(errorText(e));setNeedsRefresh(true);}}finally{release();}}
 // The write is complete before reloading. Close its form first so a failed GET
 // offers only a safe refresh, never a duplicate POST or DELETE retry.
 async function refreshAfterWrite(){try{const [l,b]=await read();if(mounted.current){setLessons(l);setBells(b);setRefreshError('');setNeedsRefresh(false);}}catch(e){if(mounted.current){setRefreshError(`Изменения сохранены, но расписание не обновилось. ${errorText(e)}`);setNeedsRefresh(true);}}}
 async function save(value:Editor,body:object){if(lock.current||needsRefresh)return;lock.current=true;setPending(true);try{await api(`${base}/${value.kind}${value.item?`/${value.item.id}`:''}`,{method:value.item?'PUT':'POST',body:JSON.stringify(body)});if(mounted.current){setEditor(null);setNotice('Изменения сохранены.');}await refreshAfterWrite();}finally{release();}}
 const askDelete=(value:Editor)=>{if(blocked)return;setDeleteError('');setDeletion(value);};
 async function remove(){if(!deletion?.item||lock.current||needsRefresh)return;lock.current=true;setPending(true);setDeleteError('');try{await api(`${base}/${deletion.kind}/${deletion.item.id}`,{method:'DELETE'});if(mounted.current){setDeletion(null);setNotice('Запись удалена.');}await refreshAfterWrite();}catch(e){if(mounted.current)setDeleteError(errorText(e));}finally{release();}}
 async function reorder(ids:string[]){if(lock.current||needsRefresh||!teacher||ids.every((id,index)=>todayLessons[index]?.id===id))return;const previous=lessons,selectedDay=day;lock.current=true;setPending(true);setOrderError('');setNotice('Сохраняем порядок…');const positions=new Map(ids.map((id,index)=>[id,index+1]));setLessons(old=>old.map(l=>l.dayOfWeek===selectedDay?{...l,lessonNumber:positions.get(l.id)??l.lessonNumber}:l));try{const next=await api<Lesson[]>(`${base}/lessons/order`,{method:'PUT',body:JSON.stringify({dayOfWeek:selectedDay,lessonIds:ids})});if(mounted.current){setLessons(next);setNotice('Порядок уроков сохранён.');}}catch(e){if(mounted.current){setLessons(previous);setOrderError(`Не удалось сохранить порядок. ${errorText(e)}`);setNotice('Порядок не изменён.');setNeedsRefresh(true);}}finally{release();}}
 return <div className="schedule-page"><div className="page-heading"><div><span className="eyebrow">УЧЕБНАЯ НЕДЕЛЯ</span><h1>Расписание <span className="heading-spark">✦</span></h1><p>Каждый урок — на своём месте. Всё для спокойного учебного дня.</p></div>{teacher&&!loading&&!error&&<Button disabled={blocked||todayLessons.length>=20} onClick={()=>setEditor({kind:'lessons'})}><Plus size={17}/>Добавить урок</Button>}</div>
 <p className="sr-only" role="status">{notice}</p>
 {loading?<p role="status" className="muted">Загружаем расписание…</p>:error?<><ErrorMessage message={error}/><Button disabled={pending} variant="secondary" onClick={refresh}>Попробовать ещё раз</Button></>:<>
 <div className="schedule-days" aria-label="День недели">{days.map((name,i)=><button key={name} disabled={pending} aria-pressed={day===i+1} aria-label={name} onClick={()=>{setDragging(false);setDay(i+1);}}><span className="schedule-day-long">{name}</span><span className="schedule-day-short" aria-hidden="true">{shortDays[i]}</span><small>{lessons.filter(l=>l.dayOfWeek===i+1).length||'—'}</small></button>)}</div>
 <ErrorMessage message={orderError}/><ErrorMessage message={refreshError}/>{needsRefresh&&<Button className="schedule-refresh" variant="secondary" disabled={pending} onClick={refresh}>Обновить расписание</Button>}
 <div className="schedule-columns"><section aria-label="Уроки"><div className="schedule-section-head"><div><span className="eyebrow">ПЛАН НА ДЕНЬ</span><h2>{days[day-1]}</h2></div><span className="pill">{todayLessons.length} ур.</span></div>
 {teacher&&todayLessons.length>0&&<p className="schedule-order-hint">{pending?'Сохраняем изменения…':todayLessons.length===20?'В дне 20 уроков. Перетащите за ⋮⋮ или используйте стрелки.':'Перетащите за ⋮⋮ или используйте стрелки, чтобы поменять порядок.'}</p>}
 {todayLessons.length===0?<EmptyState icon={<CalendarDays size={29}/>} title="На этот день уроков нет" description={teacher?'Добавьте первый урок — ученики и родители сразу увидят его в расписании.':'Загляните в другой день недели. Новые уроки появятся здесь, когда учитель их добавит.'} action={teacher?<Button disabled={blocked} variant="secondary" onClick={()=>setEditor({kind:'lessons'})}><Plus size={16}/>Добавить урок</Button>:undefined}/>:<SortableLessonList key={day} lessons={todayLessons} bells={bells} teacher={teacher} disabled={pending||needsRefresh||editor!==null||deletion!==null} onOrder={reorder} onDragging={setDragging} onEdit={lesson=>setEditor({kind:'lessons',item:lesson})} onDelete={lesson=>askDelete({kind:'lessons',item:lesson})}/>}
 </section><aside className="schedule-bells"><div className="schedule-bells-title"><span className="tile-icon peach"><Clock3 size={22}/></span><div><h2>Звонки</h2><p>Одинаковые на всю неделю</p></div></div>{bells.length===0?<p className="schedule-bells-empty">{teacher?'Укажите время уроков — оно появится в расписании автоматически.':'Учитель пока не добавил время звонков.'}</p>:<ol>{bells.map(bell=><li key={bell.id}><span className="schedule-bell-number">{bell.lessonNumber}</span><strong>{bell.startTime} <span>—</span> {bell.endTime}</strong>{teacher&&<div className="schedule-item-actions"><button disabled={blocked} className="icon-button" aria-label={`Редактировать звонок ${bell.lessonNumber}`} onClick={()=>setEditor({kind:'bells',item:bell})}><Pencil size={14}/></button><button disabled={blocked} className="icon-button" aria-label={`Удалить звонок ${bell.lessonNumber}`} onClick={()=>askDelete({kind:'bells',item:bell})}><Trash2 size={14}/></button></div>}</li>)}</ol>}{teacher&&<Button disabled={blocked} variant="secondary" className="wide" onClick={()=>setEditor({kind:'bells'})}><Plus size={16}/>Добавить звонок</Button>}<div className="schedule-note"><BookOpen size={18}/><p>Небольшие шаги каждый день складываются в большие знания.</p></div></aside></div></>}
 {editor&&<ScheduleEditor editor={editor} day={day} onClose={()=>setEditor(null)} onSave={save}/>}
 {deletion&&<Dialog title={deletion.kind==='lessons'?'Удалить урок?':'Удалить звонок?'} onClose={()=>{if(!pending)setDeletion(null);}}><p>{deletion.kind==='lessons'?'Урок исчезнет из расписания у всех участников класса. Остальные уроки сдвинутся по порядку.':'Уроки останутся в расписании, но их время больше не будет отображаться.'}</p><ErrorMessage message={deleteError}/><div className="form-actions"><Button variant="secondary" disabled={pending} onClick={()=>setDeletion(null)}>Отмена</Button><Button variant="danger" disabled={pending} onClick={remove}>{pending?'Удаляем…':'Удалить'}</Button></div></Dialog>}
 </div>;
}
function ScheduleEditor({editor,day,onClose,onSave}:{editor:Editor;day:number;onClose:()=>void;onSave:(editor:Editor,body:object)=>Promise<void>}){
 const item=editor.item,isLesson=editor.kind==='lessons';
 const [number,setNumber]=useState(item?.lessonNumber??1),[selectedDay,setSelectedDay]=useState(editor.kind==='lessons'?editor.item?.dayOfWeek??day:day);
 const [subject,setSubject]=useState(editor.kind==='lessons'?editor.item?.subject??'':''),[room,setRoom]=useState(editor.kind==='lessons'?editor.item?.room??'':'');
 const [start,setStart]=useState(editor.kind==='bells'?editor.item?.startTime??'08:00':'08:00'),[end,setEnd]=useState(editor.kind==='bells'?editor.item?.endTime??'08:45':'08:45');
 const [pending,setPending]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setPending(true);setError('');try{await onSave(editor,isLesson?{dayOfWeek:selectedDay,subject,room}:{lessonNumber:number,startTime:start,endTime:end});}catch(e){setError(errorText(e));}finally{lock.current=false;setPending(false);}}
 return <Dialog title={`${item?'Редактировать':'Добавить'} ${isLesson?'урок':'звонок'}`} onClose={()=>{if(!pending)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/>{isLesson?<><label className="field"><span>День недели</span><select disabled={pending} value={selectedDay} onChange={e=>setSelectedDay(Number(e.target.value))}>{days.map((name,i)=><option key={name} value={i+1}>{name}</option>)}</select></label><p className="schedule-form-note">{item?'При смене дня урок добавится в конец нового дня.':'Урок добавится в конец выбранного дня. Порядок можно изменить перетаскиванием.'}</p><Input label="Предмет" disabled={pending} required maxLength={120} placeholder="Например, математика" autoFocus value={subject} onChange={e=>setSubject(e.target.value)}/><Input label="Кабинет · необязательно" disabled={pending} maxLength={60} placeholder="Например, 204 или спортзал" value={room} onChange={e=>setRoom(e.target.value)}/></>:<><Input label="Номер урока" disabled={pending} type="number" min={1} max={20} required value={number} onChange={e=>setNumber(Number(e.target.value))}/><div className="form-grid"><Input label="Начало" disabled={pending} type="time" required value={start} onChange={e=>setStart(e.target.value)}/><Input label="Окончание" disabled={pending} type="time" required value={end} onChange={e=>setEnd(e.target.value)}/></div></>}<div className="form-actions"><Button type="button" variant="secondary" disabled={pending} onClick={onClose}>Отмена</Button><Button type="submit" disabled={pending}>{pending?'Сохраняем…':'Сохранить'}</Button></div></form></Dialog>;
}
