import {useEffect,useState,type FormEvent} from 'react';
import {BookOpen,Clock3,DoorOpen,Pencil,Plus,Trash2,CalendarDays} from 'lucide-react';
import {api} from '../../core/api';
import {useClassroom} from '../../core/classroom';
import {useSession} from '../../core/session';
import {Button,Dialog,EmptyState,ErrorMessage,Input} from '../../core/ui';
import './schedule.css';
type Lesson={id:string;classId:string;dayOfWeek:number;lessonNumber:number;subject:string;room:string};
type Bell={id:string;classId:string;lessonNumber:number;startTime:string;endTime:string};
type Editor={kind:'lessons';item?:Lesson}|{kind:'bells';item?:Bell};
const days=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const shortDays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const errorText=(e:unknown)=>e instanceof Error?e.message:'Не удалось выполнить запрос. Попробуйте ещё раз.';
export default function SchedulePage(){const {classId}=useClassroom();return <Schedule key={classId} classId={classId}/>;}
function Schedule({classId}:{classId:string}){
 const {user}=useSession(),teacher=user?.role==='teacher';
 const [lessons,setLessons]=useState<Lesson[]>([]),[bells,setBells]=useState<Bell[]>([]),[day,setDay]=useState((new Date().getDay()+6)%7+1);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[editor,setEditor]=useState<Editor|null>(null);
 const [deletion,setDeletion]=useState<Editor|null>(null),[pending,setPending]=useState(false),[deleteError,setDeleteError]=useState('');
 const base=`/api/classes/${classId}`;
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([api<Lesson[]>(`${base}/lessons`),api<Bell[]>(`${base}/bells`)]).then(([l,b])=>{if(active){setLessons(l);setBells(b);}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[base,attempt]);
 const todayLessons=lessons.filter(l=>l.dayOfWeek===day).sort((a,b)=>a.lessonNumber-b.lessonNumber);
 const saved=(kind:Editor['kind'],item:Lesson|Bell)=>{if(kind==='lessons')setLessons(old=>[...old.filter(l=>l.id!==item.id),item as Lesson]);else setBells(old=>[...old.filter(b=>b.id!==item.id),item as Bell].sort((a,b)=>a.lessonNumber-b.lessonNumber));setEditor(null);};
 const askDelete=(value:Editor)=>{setDeleteError('');setDeletion(value);};
 async function remove(){if(!deletion?.item||pending)return;setPending(true);setDeleteError('');try{await api(`${base}/${deletion.kind}/${deletion.item.id}`,{method:'DELETE'});if(deletion.kind==='lessons')setLessons(old=>old.filter(l=>l.id!==deletion.item?.id));else setBells(old=>old.filter(b=>b.id!==deletion.item?.id));setDeletion(null);}catch(e){setDeleteError(errorText(e));}finally{setPending(false);}}
 return <div className="schedule-page"><div className="page-heading"><div><span className="eyebrow">УЧЕБНАЯ НЕДЕЛЯ</span><h1>Расписание <span className="heading-spark">✦</span></h1><p>Каждый урок — на своём месте. Всё для спокойного учебного дня.</p></div>{teacher&&!loading&&!error&&<Button onClick={()=>setEditor({kind:'lessons'})}><Plus size={17}/>Добавить урок</Button>}</div>
 {loading?<p role="status" className="muted">Загружаем расписание…</p>:error?<><ErrorMessage message={error}/><Button variant="secondary" onClick={()=>setAttempt(n=>n+1)}>Попробовать ещё раз</Button></>:<>
 <div className="schedule-days" aria-label="День недели">{days.map((name,i)=><button key={name} aria-pressed={day===i+1} aria-label={name} onClick={()=>setDay(i+1)}><span className="schedule-day-long">{name}</span><span className="schedule-day-short" aria-hidden="true">{shortDays[i]}</span><small>{lessons.filter(l=>l.dayOfWeek===i+1).length||'—'}</small></button>)}</div>
 <div className="schedule-columns"><section aria-label="Уроки"><div className="schedule-section-head"><div><span className="eyebrow">ПЛАН НА ДЕНЬ</span><h2>{days[day-1]}</h2></div><span className="pill">{todayLessons.length} ур.</span></div>
 {todayLessons.length===0?<EmptyState icon={<CalendarDays size={29}/>} title="На этот день уроков нет" description={teacher?'Добавьте первый урок — ученики и родители сразу увидят его в расписании.':'Загляните в другой день недели. Новые уроки появятся здесь, когда учитель их добавит.'} action={teacher?<Button variant="secondary" onClick={()=>setEditor({kind:'lessons'})}><Plus size={16}/>Добавить урок</Button>:undefined}/>:<div className="schedule-lessons">{todayLessons.map((lesson,i)=>{const bell=bells.find(b=>b.lessonNumber===lesson.lessonNumber);return <article className="schedule-lesson" key={lesson.id}><div className={`schedule-number schedule-tone-${i%3}`}>{lesson.lessonNumber}<small>урок</small></div><div className="schedule-lesson-body"><h3>{lesson.subject}</h3><div className="schedule-meta"><span><Clock3 size={14}/>{bell?`${bell.startTime} — ${bell.endTime}`:'Время не задано'}</span>{lesson.room&&<span><DoorOpen size={14}/>{lesson.room}</span>}</div></div>{teacher&&<div className="schedule-item-actions"><button className="icon-button" aria-label={`Редактировать урок ${lesson.lessonNumber}: ${lesson.subject}`} onClick={()=>setEditor({kind:'lessons',item:lesson})}><Pencil size={16}/></button><button className="icon-button" aria-label={`Удалить урок ${lesson.lessonNumber}: ${lesson.subject}`} onClick={()=>askDelete({kind:'lessons',item:lesson})}><Trash2 size={16}/></button></div>}</article>;})}</div>}
 </section><aside className="schedule-bells"><div className="schedule-bells-title"><span className="tile-icon peach"><Clock3 size={22}/></span><div><h2>Звонки</h2><p>Одинаковые на всю неделю</p></div></div>{bells.length===0?<p className="schedule-bells-empty">{teacher?'Укажите время уроков — оно появится в расписании автоматически.':'Учитель пока не добавил время звонков.'}</p>:<ol>{bells.map(bell=><li key={bell.id}><span className="schedule-bell-number">{bell.lessonNumber}</span><strong>{bell.startTime} <span>—</span> {bell.endTime}</strong>{teacher&&<div className="schedule-item-actions"><button className="icon-button" aria-label={`Редактировать звонок ${bell.lessonNumber}`} onClick={()=>setEditor({kind:'bells',item:bell})}><Pencil size={14}/></button><button className="icon-button" aria-label={`Удалить звонок ${bell.lessonNumber}`} onClick={()=>askDelete({kind:'bells',item:bell})}><Trash2 size={14}/></button></div>}</li>)}</ol>}{teacher&&<Button variant="secondary" className="wide" onClick={()=>setEditor({kind:'bells'})}><Plus size={16}/>Добавить звонок</Button>}<div className="schedule-note"><BookOpen size={18}/><p>Небольшие шаги каждый день складываются в большие знания.</p></div></aside></div></>}
 {editor&&<ScheduleEditor editor={editor} day={day} base={base} onClose={()=>setEditor(null)} onSaved={saved}/>}
 {deletion&&<Dialog title={deletion.kind==='lessons'?'Удалить урок?':'Удалить звонок?'} onClose={()=>{if(!pending)setDeletion(null);}}><p>{deletion.kind==='lessons'?'Урок исчезнет из расписания у всех участников класса.':'Уроки останутся в расписании, но их время больше не будет отображаться.'}</p><ErrorMessage message={deleteError}/><div className="form-actions"><Button variant="secondary" disabled={pending} onClick={()=>setDeletion(null)}>Отмена</Button><Button variant="danger" disabled={pending} onClick={remove}>{pending?'Удаляем…':'Удалить'}</Button></div></Dialog>}
 </div>;
}
function ScheduleEditor({editor,day,base,onClose,onSaved}:{editor:Editor;day:number;base:string;onClose:()=>void;onSaved:(kind:Editor['kind'],item:Lesson|Bell)=>void}){
 const item=editor.item,isLesson=editor.kind==='lessons';
 const [number,setNumber]=useState(item?.lessonNumber??1),[selectedDay,setSelectedDay]=useState(editor.kind==='lessons'?editor.item?.dayOfWeek??day:day);
 const [subject,setSubject]=useState(editor.kind==='lessons'?editor.item?.subject??'':''),[room,setRoom]=useState(editor.kind==='lessons'?editor.item?.room??'':'');
 const [start,setStart]=useState(editor.kind==='bells'?editor.item?.startTime??'08:00':'08:00'),[end,setEnd]=useState(editor.kind==='bells'?editor.item?.endTime??'08:45':'08:45');
 const [pending,setPending]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(pending)return;setPending(true);setError('');try{const body=isLesson?{dayOfWeek:selectedDay,lessonNumber:number,subject,room}:{lessonNumber:number,startTime:start,endTime:end};const result=await api<Lesson|Bell>(`${base}/${editor.kind}${item?`/${item.id}`:''}`,{method:item?'PUT':'POST',body:JSON.stringify(body)});onSaved(editor.kind,result);}catch(e){setError(errorText(e));}finally{setPending(false);}}
 return <Dialog title={`${item?'Редактировать':'Добавить'} ${isLesson?'урок':'звонок'}`} onClose={()=>{if(!pending)onClose();}}><form onSubmit={submit}><ErrorMessage message={error}/><div className="form-grid">{isLesson&&<label className="field"><span>День недели</span><select value={selectedDay} onChange={e=>setSelectedDay(Number(e.target.value))}>{days.map((name,i)=><option key={name} value={i+1}>{name}</option>)}</select></label>}<Input label="Номер урока" type="number" min={1} max={20} required value={number} onChange={e=>setNumber(Number(e.target.value))}/></div>{isLesson?<><Input label="Предмет" required maxLength={120} placeholder="Например, математика" autoFocus value={subject} onChange={e=>setSubject(e.target.value)}/><Input label="Кабинет · необязательно" maxLength={60} placeholder="Например, 204 или спортзал" value={room} onChange={e=>setRoom(e.target.value)}/></>:<div className="form-grid"><Input label="Начало" type="time" required value={start} onChange={e=>setStart(e.target.value)}/><Input label="Окончание" type="time" required value={end} onChange={e=>setEnd(e.target.value)}/></div>}<div className="form-actions"><Button type="button" variant="secondary" disabled={pending} onClick={onClose}>Отмена</Button><Button type="submit" disabled={pending}>{pending?'Сохраняем…':'Сохранить'}</Button></div></form></Dialog>;
}
