import {token,hashToken,hashPassword} from './security.mjs';
export function registerClassroomRoutes(app,{db,requireUser,requireTeacher,accessibleStudentIds,HttpError,text,password,date,id}){
 app.use('/api/classes',requireUser);app.use('/api/students',requireUser);app.use('/api/invites',requireUser);
 const classDTO=c=>({id:c.id,name:c.name,schoolYear:c.school_year,teacherId:c.teacher_id});
 const studentDTO=(s,user)=>({id:s.id,classId:s.class_id,userId:s.user_id,fullName:s.full_name,login:s.login,birthDate:s.birth_date,parentName:s.parent_name,parentPhone:s.parent_phone,parentEmail:s.parent_email,...(user.role==='teacher'?{privateNote:s.private_note}:{})});
 const fields=b=>[text(b.fullName,'ФИО',160),date(b.birthDate??'','Дата рождения',false),text(b.parentName??'','Имя родителя',160,false),text(b.parentPhone??'','Телефон',40,false),text(b.parentEmail??'','Email родителя',254,false),text(b.privateNote??'','Заметка',3000,false)];
 app.get('/api/classes',(req,res)=>{let rows;if(req.user.role==='teacher')rows=db.prepare('SELECT * FROM classes WHERE teacher_id=? ORDER BY created_at').all(req.user.id);else if(req.user.role==='student')rows=db.prepare('SELECT c.* FROM classes c JOIN students s ON s.class_id=c.id WHERE s.user_id=?').all(req.user.id);else rows=db.prepare('SELECT DISTINCT c.* FROM classes c JOIN students s ON s.class_id=c.id JOIN parent_links p ON p.student_id=s.id WHERE p.parent_id=?').all(req.user.id);res.json(rows.map(classDTO));});
 app.post('/api/classes',(req,res)=>{if(req.user.role!=='teacher')throw new HttpError(403,'Создание класса доступно учителю');const c={id:id(),name:text(req.body.name,'Название класса',80),school_year:text(req.body.schoolYear,'Учебный год',30),teacher_id:req.user.id};db.prepare('INSERT INTO classes VALUES(?,?,?,?,?)').run(c.id,c.teacher_id,c.name,c.school_year,new Date().toISOString());res.status(201).json(classDTO(c));});
 app.get('/api/classes/:id/students',(req,res)=>{const ids=accessibleStudentIds(req.user,req.params.id);res.json(db.prepare('SELECT s.*,u.login FROM students s JOIN users u ON s.user_id=u.id WHERE s.class_id=? ORDER BY s.full_name').all(req.params.id).filter(s=>ids.includes(s.id)).map(s=>studentDTO(s,req.user)));});
 app.post('/api/classes/:id/students',(req,res)=>{requireTeacher(req.user,req.params.id);const f=fields(req.body),login=text(req.body.login,'Логин',80).toLowerCase();if(!/^[a-z0-9._-]{3,80}$/.test(login))throw new HttpError(400,'Логин: от 3 символов, латиница, цифры, точка, дефис');const pw=password(req.body.password);if(db.prepare('SELECT id FROM users WHERE login=?').get(login))throw new HttpError(409,'Этот логин уже занят');const userId=id(),studentId=id();db.exec('BEGIN');try{db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(userId,'student',login,f[0],hashPassword(pw),new Date().toISOString());db.prepare('INSERT INTO students VALUES(?,?,?,?,?,?,?,?,?)').run(studentId,req.params.id,userId,...f);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}const s=db.prepare('SELECT s.*,u.login FROM students s JOIN users u ON s.user_id=u.id WHERE s.id=?').get(studentId);res.status(201).json(studentDTO(s,req.user));});
 app.put('/api/classes/:id/students/:studentId',(req,res)=>{requireTeacher(req.user,req.params.id);const s=db.prepare('SELECT * FROM students WHERE id=? AND class_id=?').get(req.params.studentId,req.params.id);if(!s)throw new HttpError(404,'Ученик не найден');const f=fields(req.body);db.prepare('UPDATE students SET full_name=?,birth_date=?,parent_name=?,parent_phone=?,parent_email=?,private_note=? WHERE id=?').run(...f,s.id);db.prepare('UPDATE users SET name=? WHERE id=?').run(f[0],s.user_id);res.json(studentDTO({...db.prepare('SELECT * FROM students WHERE id=?').get(s.id),login:db.prepare('SELECT login FROM users WHERE id=?').get(s.user_id).login},req.user));});
 app.post('/api/students/:id/invites',(req,res)=>{const s=db.prepare('SELECT * FROM students WHERE id=?').get(req.params.id);if(!s)throw new HttpError(404,'Ученик не найден');requireTeacher(req.user,s.class_id);const raw=token(),expiresAt=new Date(Date.now()+48*3600000).toISOString();db.prepare('INSERT INTO invites VALUES(?,?,?,NULL)').run(hashToken(raw),s.id,expiresAt);res.status(201).json({token:raw,expiresAt});});
 app.post('/api/invites/accept',(req,res)=>{if(req.user.role!=='parent')throw new HttpError(403,'Войдите в аккаунт родителя');const hash=hashToken(text(req.body.token,'Приглашение',128)),invite=db.prepare('SELECT * FROM invites WHERE token_hash=? AND consumed_at IS NULL AND expires_at>?').get(hash,new Date().toISOString());if(!invite)throw new HttpError(410,'Приглашение истекло или уже использовано');db.exec('BEGIN');try{db.prepare('INSERT OR IGNORE INTO parent_links VALUES(?,?)').run(req.user.id,invite.student_id);db.prepare('UPDATE invites SET consumed_at=? WHERE token_hash=?').run(new Date().toISOString(),hash);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}res.json({studentId:invite.student_id});});
}
